### ISSUE TITLE
set locale in ApplicationController

### ISSUE THREAD

**Issue by hl** [yoolk/themes_on_rails#13]
first off, great gem

second, I think it's good to state in the read me that setting a default in `application.rb` or a custom initializer does not work when using this gem (it sets the default locale to :en)

however you can still set it in the `application_controller.rb` (as stated in the Rails doc)

``` rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  theme :theme_resolver
  before_action :set_locale

  private
  def theme_resolver
    ENV['APP_THEME'] || Settings.theme
  end

  def set_locale
    I18n.locale = Settings.locale
  end
end
```
- Settings is `rails_config`

**Comment by bastengao** [comment]
Expect this issue #14 to release in new version, i have a trouble with it.
