### ISSUE TITLE
Missing Templates 

### ISSUE THREAD

**Issue by DenisKhomusyak** [yoolk/themes_on_rails#17]
Every time I create a controller, I need to transfer files to a folder of the controller to the theme? No function built-in?

Example:

$ rails g themes_on_rails:generatelayouts SomeController

Just does'not exists in doc. about this.Thx.

**Comment by chamnap** [comment]
I'm not really sure what you mean.

**Comment by chamnap** [comment]
No built-in function, you can custom generator on your own if needed.
