### ISSUE TITLE
Include default assets in themes

### ISSUE THREAD

**Issue by luisfontes19** [yoolk/themes_on_rails#22]
By default,  scripts images and styles in assets folder should be loaded... 
For example, I have a chart.js in my asset folder, that will be used independent of the theme... I should't need to put a copy on each theme...

Is there a workaround for this?

**Comment by carp47** [comment]
You can include your default assets in your layout just as you would outside of your theme:

    <%= javascript_include_tag :application %>
    <%= javascript_include_tag "your_theme/all" %>

**Comment by luisfontes19** [comment]
Thats perfect, thanks 

Great gem, by the way

**Comment by louman** [comment]
Sorry for reopening this issue, but what about images?

Let's say I want to have a set of default images and only want to overwrite some in my theme. Is there a way to achieve this and still use:

```
# looks for the image in assets/images/default and mytheme/assets/images 
<%= image_tag 'image.jpg' %>
```

Is that possible?

**Comment by chamnap** [comment]
@louman, Is not possible. However, you can write a small rails helper in this case on your own. I don't want to touch the rails api.
