### ISSUE TITLE
How to let user switch the themes 

### ISSUE THREAD

**Issue by mazharoddin** [yoolk/themes_on_rails#23]
Hi, 
Thanks for the nice gem, its easy to use ...but can you please let me know how to let user switch the themes using some kind of theme switcher ..it would be great help if you can share some  sample code for theme switcher ..also pls let me know if its possible to let user edit css or html from his account..Thanks

**Comment by chamnap** [comment]
Please, go through the `README.md`.

**Comment by chamnap** [comment]
Currently, this gem doesn't allow user to edit css/html on his own.

**Comment by mazharoddin** [comment]
Thanks for your reply ..yeah gone through the README file, but unable to understand how to provide option to user changeable  themes ...I will explore further thanks.

**Comment by chamnap** [comment]
You can use a symbol to defer the choice of theme until a request is processed:
```
class HomeController < ApplicationController
  theme :theme_resolver

  def index
    ...
  end

  private

    def theme_resolver
      params[:theme].presence || 'professional'
    end
end
```
Now, if there is a params[:theme], it will use that theme. Otherwise, it will use professional theme.

**Comment by mazharoddin** [comment]
Thank, I will try this.
