### ISSUE TITLE
Production custom assets precompile

### ISSUE THREAD

**Issue by Svashta** [yoolk/themes_on_rails#24]
Hi,

i'm struggling with a production precompilation of custom assets.
I'm on Rails 4.2.1

For example, there are "controller" javascript files which need to be precompiled as they are not in application.js, but i can't find a way to do it. Same goes for custom stylesheets.

Any tips?

**Comment by Svashta** [comment]
Nevermind. Figured it out.

**Comment by chamnap** [comment]
Cool. It's rails specific.
