### ISSUE TITLE
Publish new release

### ISSUE THREAD

**Issue by bastengao** [yoolk/themes_on_rails#26]
The `i18n.default_locale` configuration is also in latest version, bug it is fixed in master. Please publish new release.

**Comment by n-rodriguez** [comment]
+1 (please!)

**Comment by chamnap** [comment]
The new gem is released, https://rubygems.org/gems/themes_on_rails/versions/0.3.1.

@n-rodriguez, what do you mean?
> update doc about the prepend: (true | false) option

**Comment by n-rodriguez** [comment]
https://github.com/yoolk/themes_on_rails/blob/master/lib/themes_on_rails/action_controller.rb#L36
