### ISSUE TITLE
inline theme proc got error

### ISSUE THREAD

**Issue by wuwx** [yoolk/themes_on_rails#27]
i am use rails 4.2.4
my controller code like this
```ruby
class Sites::ApplicationController < ::ApplicationController
  before_action :set_site
  #theme Proc.new { |controller| @site.theme || 'default' }
  theme Proc.new { |controller| params[:theme].presence || 'professional' }

  private
    def set_site
      @site ||= Site.find(params[:site_id])
    end
end
```

but got error:

undefined local variable or method `params' for Sites::ApplicationController:Class

**Comment by chamnap** [comment]
You need to access from `controller`.

>  theme Proc.new { |controller| controller.params[:theme].presence || 'professional' }
