### ISSUE TITLE
Using Themes_on_rails and Liquid together

### ISSUE THREAD

**Issue by samsoft00** [yoolk/themes_on_rails#32]
@chamnap  and others, kindly help out, i'm new to ruby on rails, i'm currently working on a project that required user to have a sub-domain under the main website, i'm currently using theme_on_rails to create themes but don't know how i can bring together, the templates (html and CSS) which reside on theme directory and Liquid engine.

i'll appreciate your help.

regards

**Comment by chamnap** [comment]
Just add 

`gem 'liquid-rails'`

It will work.

**Comment by samsoft00** [comment]
Thanks @chamnap i've done exactly but after loading the theme, it still make reference to the default page. {{ content_for_layout }} is loading from the main view not from the themes. do i need to adjust anything in the router? and how do i handle action name, example subdomain.domain.com/register?
