### ISSUE TITLE
chamnapchhorn@gmail.com Can I place theme method in application controller?

### ISSUE THREAD

**Issue by saumyamehta17** [yoolk/themes_on_rails#33]
@chamnap  - Its giving error if I do so. Any help.

**Comment by yogeshjain999** [comment]
It works even if we call `theme` in `ApplicationController`.

@sweetymehta could you provide more details on this ? Like what error you are getting and how you are calling `theme`.

**Comment by chamnap** [comment]
Can you check this example repo, https://github.com/chamnap/themes_on_rails_example?

**Comment by saumyamehta17** [comment]
@yogeshjain999 I was using it with locomotivecms engine where I found an error undefined method theme for appliction controller. 
@chamnap yeah I checked that too. May be issue with Locomotivecms Engine.

Anyways I changed the way to solve it. Thanks

**Comment by chamnap** [comment]
Cool
