### ISSUE TITLE
NoMethodError: undefined method `theme' for ApplicationController:Class

### ISSUE THREAD

**Issue by nlsrchtr** [yoolk/themes_on_rails#34]
Thanks for your nice work on this theme gem. It's nice to use. Sadly we hit this bug, adding the `theme` method to our `ApplicationController`: `NoMethodError: undefined method`theme' for ApplicationController:Class`.

Adding the method on a different controller makes no problems at all. But since we have for example `Devise` inheriting from the `ApplicationController` and we would like to use theming also for the registration etc. views, we need it inside the `ApplicationController`.

You can find a stacktrace of the exception at this [gist](https://gist.github.com/nlsrchtr/c44895c9d26d4aa7a30a38efbb0b8c85). I think it's some dependency problem with Devise, ActiveAdmin or InheritedResources. I tried moving your gem to the top of the `Gemfile`, but this doesn't changed anything.

Would be great if you could have a look into this.

Thanks for your time and effort!

**Comment by chamnap** [comment]
I've this gem on production for ages on both rails 3 and 4 with `Devise`. Never have that problem running with several thousand websites. 
Yeah, I haven't tried with `ActiveAdmin` or `InheritedResources`. `ActiveAdmin` is very complicated. 

I'm sorry. I'm too busy at the moment. What this gem does is add `before_filter`. Have a look on  this example application, https://github.com/chamnap/themes_on_rails_example.

**Comment by softbeehive** [comment]
Hi @chamnap,
Thanks for your feedback, the issue described by @nlsrchtr occurs on `rails server`, while adding `theme` to ApplicationController without restarting server doesn't produce any error.

**Comment by chamnap** [comment]
Can you create a sample repo @softbeehive? I can't reproduce it basically.

**Comment by nlsrchtr** [comment]
Thanks for taking time to give some feedback @chamnap! Since the error indicates, that the method `theme` is not defined, it looks like the loading is somehow broken.

I found a solution be adding the concern manually to the `ApplicationController`:

``` ruby
include ::ThemesOnRails::ControllerAdditions
theme :current_theme, only: :html
```

Maybe this helps you or someone else to dig deeper why this happens.

**Comment by chamnap** [comment]
There is an initializer, https://github.com/chamnap/themes_on_rails/blob/master/lib/themes_on_rails/engine.rb#L5, where it loads `::ThemesOnRails::ControllerAdditions`.
