### ISSUE TITLE
Unable to clear the browsers cache when using themes

### ISSUE THREAD

**Issue by PavanOnRails** [yoolk/themes_on_rails#35]
In a normal application(without themes), the below code is used to clear the browsers cache

```
class ApplicationController < ActionController::Base

before_filter :set_cache_headers

  private

  def set_cache_headers
    response.headers["Cache-Control"] = "no-cache, no-store"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end
end
```
so that to prevent the pages to be viewed by clicking the browsers back button after user signout. But with themes, i'm unable to get that above code working. Please help me out. Thanks.

**Comment by chamnap** [comment]
I don't believe this is because of `themes_on_rails`. What this gem does is only find the view path of the theme, and it doesn't nothing else.

Please, feel to reopen it if you have more inputs.
